### PR TITLE
[Grupo BC6] Scraping

### LINKED ISSUE #16: [Grupo BC6] Scraping
Implementar funcionalidade que permite fazer scraping a websites de vinho. Deverão ser suportados pelo menos três websites diferentes.

### PR DESCRIPTION
**Pull request by nuoliveira**
Resolves #16.

## Notable Changes
- Added [AngleSharp](https://github.com/AngleSharp/AngleSharp) as a dependency
- Created `ScrapedWine` model
- Created `ScrapingController`
- Created `Scraping` view

## Supported Websites
- https://www.garrafeiranacional.com
- https://infovini.com
- https://www.lojadovinho.com
- https://www.vinhedo.pt
- https://wine.pt
- https://winestuff.pt

### CODE REVIEW

**Review by joaopferreira19 — CHANGES_REQUESTED** [review]
Before checking any further, please fix the merging conflicts.

**Review by joaopferreira19 — CHANGES_REQUESTED** [review]
Using the frontend form, it gives me this error:

imagem

Through the swagger api testing, gives me this one:

`Value cannot be null. (Parameter 'node')`

Try to fix it as soon as possible

**Review by joaopferreira19 — APPROVED** [review]
Problem was on the url, it only works with wine pages and I did not know.

Approving merge.

**Review by joaopferreira19 — APPROVED** [review]
Fix the merge conflicts so I can merge.

**Comment by nuoliveira** [comment]
Integrated the latest changes so the merge can proceed.

**Pull request merged**
