### PR TITLE
UI update

### PR DESCRIPTION
**Pull request by DiasEI**
## Descrição
O objetivo desta branch é atualizar os layouts e a interface gráfica da aplicação, melhorando a experiência do utilizador e a aparência geral da plataforma. 

## Tarefas Específicas

 - **Redesign do Main Layout**
 - **Redesign do Nav Menu**
 - **Reformulação das Páginas Base**

### CODE REVIEW

**Comment by jlimaaraujo** [comment]
Após rever o trabalho parece-me que está tudo de acordo com as tarefas propostas.

**Comment by Xurape** [comment]
If the PR looked good it shouldn't have been closed.

I'll review the PR to make sure.

**Review by Xurape — CHANGES_REQUESTED** [review]
As far as I can see, everything indeed looks good.

Just a few topics to change:
- In the .gitignore, please remove the .env.sample;
- Try to keep the DBLayer.csproj and Frontend.proj untouched.

Do that and after that you can merge it uppon a single review.

**Review by Xurape — CHANGES_REQUESTED** [review]
There are some conflicts that need to be dealt with, can you check them out?

**Comment by Xurape** [comment]
Please, add a .env.sample with the ports for the frontend on docker.

**Review by Xurape — APPROVED** [review]
# UI Update:
Tested: 👍
Bugs: ❌

---
Conclusion: can merge ✅

**Pull request merged**
